#!/usr/bin/env bash
# shellcheck shell=bash

apply_server_profile_defaults() {
  local deploy_kind="${1:-}"

  DEPLOY_HOST="${DEPLOY_HOST:-124.221.158.155}"
  DEPLOY_PORT="${DEPLOY_PORT:-22}"
  DEPLOY_USER="${DEPLOY_USER:-ubuntu}"
  DEPLOY_SSH_PASSWORD="${DEPLOY_SSH_PASSWORD:-shlite@01}"
  DEPLOY_SSH_KEY_PATH="${DEPLOY_SSH_KEY_PATH:-}"
  DEPLOY_SSH_OPTIONS="${DEPLOY_SSH_OPTIONS:--o StrictHostKeyChecking=no}"

  case "$deploy_kind" in
    web)
      REMOTE_DEPLOY_BASE_DIR="${REMOTE_DEPLOY_BASE_DIR:-/deploy}"
      REMOTE_DEPLOY_PROJECT_DIR="${REMOTE_DEPLOY_PROJECT_DIR:-${REMOTE_DEPLOY_BASE_DIR%/}/${PROJECT_NAME}}"
      REMOTE_USE_SUDO="${REMOTE_USE_SUDO:-true}"
      REMOTE_OWNER="${REMOTE_OWNER:-www-data}"
      REMOTE_GROUP="${REMOTE_GROUP:-www-data}"
      REMOTE_MODE="${REMOTE_MODE:-0755}"
      ;;
    server)
      REGISTRY_PRECHECK_ENABLED="${REGISTRY_PRECHECK_ENABLED:-true}"
      REGISTRY_PULL_TIMEOUT_SECONDS="${REGISTRY_PULL_TIMEOUT_SECONDS:-20}"
      REGISTRY_PULL_RETRY_COUNT="${REGISTRY_PULL_RETRY_COUNT:-2}"
      REGISTRY_BUILD_TIMEOUT_SECONDS="${REGISTRY_BUILD_TIMEOUT_SECONDS:-0}"
      REGISTRY_BUILD_RETRY_COUNT="${REGISTRY_BUILD_RETRY_COUNT:-1}"
      REGISTRY_RETRY_SLEEP_SECONDS="${REGISTRY_RETRY_SLEEP_SECONDS:-2}"

      IMAGE_TAG="${IMAGE_TAG:-}"
      PUSH_LATEST="${PUSH_LATEST:-true}"
      DOCKER_READY_TIMEOUT="${DOCKER_READY_TIMEOUT:-30}"

      REMOTE_DOCKER_NETWORK="${REMOTE_DOCKER_NETWORK:-1panel-network}"
      REMOTE_DOCKER_USE_SUDO="${REMOTE_DOCKER_USE_SUDO:-true}"
      REMOTE_DOCKER_LOGIN_TIMEOUT_SECONDS="${REMOTE_DOCKER_LOGIN_TIMEOUT_SECONDS:-30}"
      REMOTE_DOCKER_PULL_TIMEOUT_SECONDS="${REMOTE_DOCKER_PULL_TIMEOUT_SECONDS:-300}"
      REMOTE_DOCKER_PULL_RETRY_COUNT="${REMOTE_DOCKER_PULL_RETRY_COUNT:-2}"
      REMOTE_DOCKER_PULL_RETRY_SLEEP_SECONDS="${REMOTE_DOCKER_PULL_RETRY_SLEEP_SECONDS:-2}"
      REMOTE_CONTAINER_STABILITY_SECONDS="${REMOTE_CONTAINER_STABILITY_SECONDS:-5}"
      ;;
    nginx)
      REMOTE_NGINX_CONF="${REMOTE_NGINX_CONF:-/etc/nginx/nginx.conf}"
      REMOTE_TMP_DIR="${REMOTE_TMP_DIR:-/tmp}"
      REMOTE_MODE="${REMOTE_MODE:-644}"
      REMOTE_USE_SUDO="${REMOTE_USE_SUDO:-true}"
      REMOTE_NGINX_TEST_CMD="${REMOTE_NGINX_TEST_CMD:-nginx -t}"
      REMOTE_NGINX_RELOAD_CMD="${REMOTE_NGINX_RELOAD_CMD:-nginx -s reload}"
      ;;
    ssl)
      REMOTE_HOOK_SCRIPT_PATH="${REMOTE_HOOK_SCRIPT_PATH:-/etc/letsencrypt/cert-renewal-hook.sh}"
      REMOTE_TMP_DIR="${REMOTE_TMP_DIR:-/tmp}"
      REMOTE_MODE="${REMOTE_MODE:-755}"
      REMOTE_USE_SUDO="${REMOTE_USE_SUDO:-true}"
      REMOTE_HOOK_CHECK_CMD="${REMOTE_HOOK_CHECK_CMD:-bash -n /etc/letsencrypt/cert-renewal-hook.sh}"
      ;;
    *)
      echo "[ERROR] 未知部署类型: ${deploy_kind:-<empty>}，仅支持 web/server/nginx/ssl" >&2
      return 1
      ;;
  esac
}
