// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authSessionsFieldNames          = builder.RawFieldNames(&AuthSessions{})
	authSessionsRows                = strings.Join(authSessionsFieldNames, ",")
	authSessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(authSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authSessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(authSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	authSessionsModel interface {
		Insert(ctx context.Context, data *AuthSessions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AuthSessions, error)
		FindOneByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (*AuthSessions, error)
		Update(ctx context.Context, data *AuthSessions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAuthSessionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AuthSessions struct {
		Id               uint64       `db:"id"`
		TenantId         uint64       `db:"tenant_id"`
		AuthUserId       uint64       `db:"auth_user_id"`
		Provider         string       `db:"provider"`
		ClientType       string       `db:"client_type"`
		RefreshTokenHash string       `db:"refresh_token_hash"`
		ExpiresAt        time.Time    `db:"expires_at"`
		RevokedAt        sql.NullTime `db:"revoked_at"`
		LastSeenAt       sql.NullTime `db:"last_seen_at"`
		MetadataJson     string       `db:"metadata_json"`
		CreatedAt        time.Time    `db:"created_at"`
		UpdatedAt        time.Time    `db:"updated_at"`
	}
)

func newAuthSessionsModel(conn sqlx.SqlConn) *defaultAuthSessionsModel {
	return &defaultAuthSessionsModel{
		conn:  conn,
		table: "`auth_sessions`",
	}
}

func (m *defaultAuthSessionsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuthSessionsModel) FindOne(ctx context.Context, id uint64) (*AuthSessions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authSessionsRows, m.table)
	var resp AuthSessions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthSessionsModel) FindOneByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (*AuthSessions, error) {
	var resp AuthSessions
	query := fmt.Sprintf("select %s from %s where `refresh_token_hash` = ? limit 1", authSessionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, refreshTokenHash)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthSessionsModel) Insert(ctx context.Context, data *AuthSessions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, authSessionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.AuthUserId, data.Provider, data.ClientType, data.RefreshTokenHash, data.ExpiresAt, data.RevokedAt, data.LastSeenAt, data.MetadataJson)
	return ret, err
}

func (m *defaultAuthSessionsModel) Update(ctx context.Context, newData *AuthSessions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authSessionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TenantId, newData.AuthUserId, newData.Provider, newData.ClientType, newData.RefreshTokenHash, newData.ExpiresAt, newData.RevokedAt, newData.LastSeenAt, newData.MetadataJson, newData.Id)
	return err
}

func (m *defaultAuthSessionsModel) tableName() string {
	return m.table
}
