// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authProviderConfigsFieldNames          = builder.RawFieldNames(&AuthProviderConfigs{})
	authProviderConfigsRows                = strings.Join(authProviderConfigsFieldNames, ",")
	authProviderConfigsRowsExpectAutoSet   = strings.Join(stringx.Remove(authProviderConfigsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authProviderConfigsRowsWithPlaceHolder = strings.Join(stringx.Remove(authProviderConfigsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	authProviderConfigsModel interface {
		Insert(ctx context.Context, data *AuthProviderConfigs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AuthProviderConfigs, error)
		FindOneByTenantIdProviderClientType(ctx context.Context, tenantId uint64, provider string, clientType string) (*AuthProviderConfigs, error)
		Update(ctx context.Context, data *AuthProviderConfigs) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAuthProviderConfigsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AuthProviderConfigs struct {
		Id             uint64       `db:"id"`
		TenantId       uint64       `db:"tenant_id"`
		Provider       string       `db:"provider"`
		ClientType     string       `db:"client_type"`
		Enabled        int64        `db:"enabled"`
		AppId          string       `db:"app_id"`
		AppSecret      string       `db:"app_secret"`
		RedirectUri    string       `db:"redirect_uri"`
		Scope          string       `db:"scope"`
		TeamId         string       `db:"team_id"`
		ClientId       string       `db:"client_id"`
		KeyId          string       `db:"key_id"`
		SigningKey     string       `db:"signing_key"`
		TestPhone      string       `db:"test_phone"`
		TestCaptcha    string       `db:"test_captcha"`
		TestCaptchaKey string       `db:"test_captcha_key"`
		ExtraJson      string       `db:"extra_json"`
		CreatedAt      sql.NullTime `db:"created_at"`
		UpdatedAt      sql.NullTime `db:"updated_at"`
	}
)

func newAuthProviderConfigsModel(conn sqlx.SqlConn) *defaultAuthProviderConfigsModel {
	return &defaultAuthProviderConfigsModel{
		conn:  conn,
		table: "`auth_provider_configs`",
	}
}

func (m *defaultAuthProviderConfigsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuthProviderConfigsModel) FindOne(ctx context.Context, id uint64) (*AuthProviderConfigs, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authProviderConfigsRows, m.table)
	var resp AuthProviderConfigs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthProviderConfigsModel) FindOneByTenantIdProviderClientType(ctx context.Context, tenantId uint64, provider string, clientType string) (*AuthProviderConfigs, error) {
	var resp AuthProviderConfigs
	query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `provider` = ? and `client_type` = ? limit 1", authProviderConfigsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, tenantId, provider, clientType)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthProviderConfigsModel) Insert(ctx context.Context, data *AuthProviderConfigs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, authProviderConfigsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.Provider, data.ClientType, data.Enabled, data.AppId, data.AppSecret, data.RedirectUri, data.Scope, data.TeamId, data.ClientId, data.KeyId, data.SigningKey, data.TestPhone, data.TestCaptcha, data.TestCaptchaKey, data.ExtraJson)
	return ret, err
}

func (m *defaultAuthProviderConfigsModel) Update(ctx context.Context, newData *AuthProviderConfigs) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authProviderConfigsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TenantId, newData.Provider, newData.ClientType, newData.Enabled, newData.AppId, newData.AppSecret, newData.RedirectUri, newData.Scope, newData.TeamId, newData.ClientId, newData.KeyId, newData.SigningKey, newData.TestPhone, newData.TestCaptcha, newData.TestCaptchaKey, newData.ExtraJson, newData.Id)
	return err
}

func (m *defaultAuthProviderConfigsModel) tableName() string {
	return m.table
}
