// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authUsersFieldNames          = builder.RawFieldNames(&AuthUsers{})
	authUsersRows                = strings.Join(authUsersFieldNames, ",")
	authUsersRowsExpectAutoSet   = strings.Join(stringx.Remove(authUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authUsersRowsWithPlaceHolder = strings.Join(stringx.Remove(authUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	authUsersModel interface {
		Insert(ctx context.Context, data *AuthUsers) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AuthUsers, error)
		Update(ctx context.Context, data *AuthUsers) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAuthUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AuthUsers struct {
		Id          uint64       `db:"id"`
		TenantId    uint64       `db:"tenant_id"`
		DisplayName string       `db:"display_name"`
		AvatarUrl   string       `db:"avatar_url"`
		Role        string       `db:"role"`
		Status      string       `db:"status"`
		LastLoginAt sql.NullTime `db:"last_login_at"`
		CreatedAt   time.Time    `db:"created_at"`
		UpdatedAt   time.Time    `db:"updated_at"`
	}
)

func newAuthUsersModel(conn sqlx.SqlConn) *defaultAuthUsersModel {
	return &defaultAuthUsersModel{
		conn:  conn,
		table: "`auth_users`",
	}
}

func (m *defaultAuthUsersModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuthUsersModel) FindOne(ctx context.Context, id uint64) (*AuthUsers, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authUsersRows, m.table)
	var resp AuthUsers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthUsersModel) Insert(ctx context.Context, data *AuthUsers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, authUsersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.DisplayName, data.AvatarUrl, data.Role, data.Status, data.LastLoginAt)
	return ret, err
}

func (m *defaultAuthUsersModel) Update(ctx context.Context, data *AuthUsers) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authUsersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.DisplayName, data.AvatarUrl, data.Role, data.Status, data.LastLoginAt, data.Id)
	return err
}

func (m *defaultAuthUsersModel) tableName() string {
	return m.table
}
