// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authTenantsFieldNames          = builder.RawFieldNames(&AuthTenants{})
	authTenantsRows                = strings.Join(authTenantsFieldNames, ",")
	authTenantsRowsExpectAutoSet   = strings.Join(stringx.Remove(authTenantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authTenantsRowsWithPlaceHolder = strings.Join(stringx.Remove(authTenantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	authTenantsModel interface {
		Insert(ctx context.Context, data *AuthTenants) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AuthTenants, error)
		FindOneByTenantKey(ctx context.Context, tenantKey string) (*AuthTenants, error)
		Update(ctx context.Context, data *AuthTenants) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAuthTenantsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AuthTenants struct {
		Id        uint64    `db:"id"`
		TenantKey string    `db:"tenant_key"`
		Name      string    `db:"name"`
		Enabled   int64     `db:"enabled"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newAuthTenantsModel(conn sqlx.SqlConn) *defaultAuthTenantsModel {
	return &defaultAuthTenantsModel{
		conn:  conn,
		table: "`auth_tenants`",
	}
}

func (m *defaultAuthTenantsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuthTenantsModel) FindOne(ctx context.Context, id uint64) (*AuthTenants, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authTenantsRows, m.table)
	var resp AuthTenants
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthTenantsModel) FindOneByTenantKey(ctx context.Context, tenantKey string) (*AuthTenants, error) {
	var resp AuthTenants
	query := fmt.Sprintf("select %s from %s where `tenant_key` = ? limit 1", authTenantsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, tenantKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthTenantsModel) Insert(ctx context.Context, data *AuthTenants) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, authTenantsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TenantKey, data.Name, data.Enabled)
	return ret, err
}

func (m *defaultAuthTenantsModel) Update(ctx context.Context, newData *AuthTenants) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authTenantsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TenantKey, newData.Name, newData.Enabled, newData.Id)
	return err
}

func (m *defaultAuthTenantsModel) tableName() string {
	return m.table
}
