// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authIdentitiesFieldNames          = builder.RawFieldNames(&AuthIdentities{})
	authIdentitiesRows                = strings.Join(authIdentitiesFieldNames, ",")
	authIdentitiesRowsExpectAutoSet   = strings.Join(stringx.Remove(authIdentitiesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authIdentitiesRowsWithPlaceHolder = strings.Join(stringx.Remove(authIdentitiesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	authIdentitiesModel interface {
		Insert(ctx context.Context, data *AuthIdentities) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AuthIdentities, error)
		FindOneByTenantIdProviderProviderSubject(ctx context.Context, tenantId uint64, provider string, providerSubject string) (*AuthIdentities, error)
		Update(ctx context.Context, data *AuthIdentities) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAuthIdentitiesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AuthIdentities struct {
		Id              uint64       `db:"id"`
		TenantId        uint64       `db:"tenant_id"`
		AuthUserId      uint64       `db:"auth_user_id"`
		Provider        string       `db:"provider"`
		ClientType      string       `db:"client_type"`
		ProviderSubject string       `db:"provider_subject"`
		UnionId         string       `db:"union_id"`
		ProfileJson     string       `db:"profile_json"`
		CreatedAt       sql.NullTime `db:"created_at"`
		UpdatedAt       sql.NullTime `db:"updated_at"`
	}
)

func newAuthIdentitiesModel(conn sqlx.SqlConn) *defaultAuthIdentitiesModel {
	return &defaultAuthIdentitiesModel{
		conn:  conn,
		table: "`auth_identities`",
	}
}

func (m *defaultAuthIdentitiesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuthIdentitiesModel) FindOne(ctx context.Context, id uint64) (*AuthIdentities, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authIdentitiesRows, m.table)
	var resp AuthIdentities
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthIdentitiesModel) FindOneByTenantIdProviderProviderSubject(ctx context.Context, tenantId uint64, provider string, providerSubject string) (*AuthIdentities, error) {
	var resp AuthIdentities
	query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `provider` = ? and `provider_subject` = ? limit 1", authIdentitiesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, tenantId, provider, providerSubject)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthIdentitiesModel) Insert(ctx context.Context, data *AuthIdentities) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, authIdentitiesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.AuthUserId, data.Provider, data.ClientType, data.ProviderSubject, data.UnionId, data.ProfileJson)
	return ret, err
}

func (m *defaultAuthIdentitiesModel) Update(ctx context.Context, newData *AuthIdentities) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authIdentitiesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TenantId, newData.AuthUserId, newData.Provider, newData.ClientType, newData.ProviderSubject, newData.UnionId, newData.ProfileJson, newData.Id)
	return err
}

func (m *defaultAuthIdentitiesModel) tableName() string {
	return m.table
}
