server:
  port: 8080
  read_timeout: 30
  write_timeout: 30
  allow_origins:
    - "*"
  allow_methods:
    - GET
    - POST
    - OPTIONS
  allow_headers:
    - Origin
    - Content-Type
    - Accept
    - Authorization

mysql:
  host: 1Panel-mysql-RHnT
  port: 3306
  user: service_runner
  password: ServiceMysql_20260312
  database: auth_service_test
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600

redis:
  addr: 1Panel-redis-PDvy:6379
  password: 6rw332GfSPWW8nBF
  db: 2
  pool_size: 10

log:
  level: debug
  file: logs/app.log

jwt:
  secret: auth-service-prod-secret-20260318
  issuer: auth_service
  access_expiry: 7200
  refresh_expiry: 7776000

auth:
  state_ttl_second: 300
  phone_captcha_ttl_second: 300
  guest_device_ttl_second: 600
  tenants:
    - key: stellar
      name: Stellar
      enabled: true
      bridge_base_url: https://stellar.xdarren.com
      bridge_auth_key: stellar-auth-bridge-20260318
      providers:
        - provider: wechat
          client_type: app
          enabled: true
          app_id: wxd5551e8aab2c8f3e
          app_secret: 7700f77852adb5d5afcf4cef5ea5ab3f
        - provider: apple
          client_type: ios
          enabled: true
          client_id: com.xdarren.stellar
          team_id: X4L9Z2674W
          key_id: 3R537T99VJ
          signing_key: |-
            -----BEGIN PRIVATE KEY-----
            MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghlPYOg+YT1sSUjCj
            I3g3M6ilr6nTeWy96QxQd0sUl42gCgYIKoZIzj0DAQehRANCAAR1k4hLlm5Ya8tM
            e2R6TQJnpeFcaiVx26o0z/NZBZjFI7dIqvsZ15HQ7meCcjw/JOx5FjfATm2UHNCz
            Edeyk1CH
            -----END PRIVATE KEY-----
        - provider: password
          client_type: app
          enabled: true
        - provider: phone
          client_type: app
          enabled: true
          test_phone: "18912345678"
          test_captcha: "1234"
          test_captcha_key: test-captcha-key
        - provider: guest
          client_type: app
          enabled: true
    - key: tinytext
      name: TinyText
      enabled: true
      bridge_base_url: https://tinytext.xdarren.com
      bridge_auth_key: tinytext-auth-bridge-20260318
      providers:
        - provider: wechat
          client_type: web
          enabled: true
          app_id: wxbb79bd2eb7ece73a
          app_secret: cc1cdc4343d24d46bfdb7dc2cf15cb06
          redirect_uri: https://tinytext.xdarren.com/wechat/callback
          scope: snsapi_login
    - key: template_project
      name: Template Project
      enabled: true
      bridge_base_url: http://124.221.158.155:8104
      bridge_auth_key: template-project-auth-bridge-20260318
      providers:
        - provider: password
          client_type: default
          enabled: true
    - key: imagen
      name: Imagen
      enabled: true
      bridge_base_url: http://124.221.158.155:8102
      bridge_auth_key: imagen-auth-bridge-20260318
      providers:
        - provider: password
          client_type: default
          enabled: true
    - key: notification
      name: Notification
      enabled: true
      bridge_base_url: http://124.221.158.155:8103
      bridge_auth_key: notification-auth-bridge-20260318
      providers:
        - provider: password
          client_type: default
          enabled: true
