#!/usr/bin/env bash
# shellcheck shell=bash

readonly DEPLOY_SERVER_BASE_IMAGE_REGISTRY_DEFAULT="docker.io"
readonly DEPLOY_SERVER_BUILDER_BASE_IMAGE_DEFAULT="library/golang:1.25.6-alpine3.22"
readonly DEPLOY_SERVER_RUNTIME_BASE_IMAGE_DEFAULT="library/alpine:3.22"

apply_deploy_server_base_image_defaults() {
  BASE_IMAGE_REGISTRY="${BASE_IMAGE_REGISTRY:-$DEPLOY_SERVER_BASE_IMAGE_REGISTRY_DEFAULT}"
  BUILDER_BASE_IMAGE="${BUILDER_BASE_IMAGE:-$DEPLOY_SERVER_BUILDER_BASE_IMAGE_DEFAULT}"
  RUNTIME_BASE_IMAGE="${RUNTIME_BASE_IMAGE:-$DEPLOY_SERVER_RUNTIME_BASE_IMAGE_DEFAULT}"
  BASE_IMAGE_REGISTRY_CANDIDATES="${BASE_IMAGE_REGISTRY_CANDIDATES:-$BASE_IMAGE_REGISTRY}"

  export BASE_IMAGE_REGISTRY BUILDER_BASE_IMAGE RUNTIME_BASE_IMAGE BASE_IMAGE_REGISTRY_CANDIDATES
}
