// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/darren-you/auth_service/template_server/internal/middleware"
	"github.com/darren-you/auth_service/template_server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/providers/:provider/callback",
				Handler: ProviderCallbackHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/auth/providers/:provider/login-url",
				Handler: GetLoginURLHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/providers/guest/device-id",
				Handler: IssueGuestDeviceIDHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/providers/password/register",
				Handler: RegisterPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/providers/phone/send-captcha",
				Handler: SendPhoneCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/refresh",
				Handler: RefreshHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/health",
				Handler: HealthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{
			middleware.NewAccessAuthMiddleware(serverCtx).Handle,
		}, rest.Route{
			Method:  http.MethodGet,
			Path:    "/api/v1/auth/me",
			Handler: MeHandler(serverCtx),
		}),
	)

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{
			middleware.NewAccessAuthMiddleware(serverCtx).Handle,
		}, rest.Route{
			Method:  http.MethodPut,
			Path:    "/api/v1/auth/me",
			Handler: UpdateMeHandler(serverCtx),
		}),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/auth/internal/users",
				Handler: InternalUpdateUserHandler(serverCtx),
			},
		},
	)
}
