// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AuthUserResp struct {
	Id          uint64 `json:"id"`
	TenantKey   string `json:"tenant_key"`
	DisplayName string `json:"display_name"`
	AvatarURL   string `json:"avatar_url"`
	Role        string `json:"role"`
	Status      string `json:"status"`
	LastLoginAt int64  `json:"last_login_at,optional"`
}

type UpdateMeReq struct {
	DisplayName string `json:"display_name,optional"`
	AvatarURL   string `json:"avatar_url,optional"`
}

type InternalUpdateUserReq struct {
	TenantKey   string `json:"tenant_key"`
	UserID      uint64 `json:"user_id"`
	DisplayName string `json:"display_name,optional"`
	AvatarURL   string `json:"avatar_url,optional"`
	Role        string `json:"role,optional"`
	Status      string `json:"status,optional"`
}

type GetLoginURLReq struct {
	Provider   string `path:"provider"`
	TenantKey  string `form:"tenant_key"`
	ClientType string `form:"client_type"`
}

type GuestDeviceIDReq struct {
	TenantKey  string `json:"tenant_key"`
	ClientType string `json:"client_type"`
}

type GuestDeviceIDResp struct {
	TenantKey  string `json:"tenant_key"`
	ClientType string `json:"client_type"`
	DeviceID   string `json:"device_id"`
	ExpiresIn  int64  `json:"expires_in"`
}

type HealthResp struct {
	Service string `json:"service"`
}

type LoginURLResp struct {
	TenantKey  string `json:"tenant_key"`
	Provider   string `json:"provider"`
	ClientType string `json:"client_type"`
	LoginURL   string `json:"login_url"`
	State      string `json:"state"`
}

type LogoutReq struct {
	RefreshToken string `json:"refresh_token"`
}

type LogoutResp struct {
	Ok bool `json:"ok"`
}

type PasswordRegisterReq struct {
	TenantKey   string `json:"tenant_key"`
	ClientType  string `json:"client_type"`
	Username    string `json:"username"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	DisplayName string `json:"display_name,optional"`
	AvatarURL   string `json:"avatar_url,optional"`
}

type PhoneCaptchaSendReq struct {
	TenantKey  string `json:"tenant_key"`
	ClientType string `json:"client_type"`
	Phone      string `json:"phone"`
}

type PhoneCaptchaSendResp struct {
	TenantKey  string `json:"tenant_key"`
	ClientType string `json:"client_type"`
	CaptchaKey string `json:"captcha_key"`
	ExpiresIn  int64  `json:"expires_in"`
}

type ProviderCallbackReq struct {
	Provider          string `path:"provider"`
	TenantKey         string `json:"tenant_key"`
	ClientType        string `json:"client_type"`
	Code              string `json:"code,optional"`
	PhoneCode         string `json:"phone_code,optional"`
	State             string `json:"state,optional"`
	AuthorizationCode string `json:"authorization_code,optional"`
	Username          string `json:"username,optional"`
	Email             string `json:"email,optional"`
	Password          string `json:"password,optional"`
	Phone             string `json:"phone,optional"`
	Captcha           string `json:"captcha,optional"`
	CaptchaKey        string `json:"captcha_key,optional"`
	Token             string `json:"token,optional"`
	Gyuid             string `json:"gyuid,optional"`
	DeviceID          string `json:"device_id,optional"`
	DisplayName       string `json:"display_name,optional"`
	AvatarURL         string `json:"avatar_url,optional"`
	CurrentUserID     uint64 `json:"current_user_id,optional"`
	CurrentUserRole   string `json:"current_user_role,optional"`
}

type RefreshReq struct {
	RefreshToken string `json:"refresh_token"`
}

type SessionResp struct {
	TenantKey    string       `json:"tenant_key"`
	Provider     string       `json:"provider"`
	ClientType   string       `json:"client_type"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token"`
	ExpiresIn    int64        `json:"expires_in"`
	User         AuthUserResp `json:"user"`
}
